version: "3.7"
services:
  app:
    build:
      context: app
      dockerfile: dev.Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: wait-for db:3306 -t 40 -- bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=node
    networks:
      - app-network
  nginx:
    build:
      context: nginx
    command: wait-for app:3000 -t 40 -- nginx -g 'daemon off;'
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network
  db:
    image: mysql:5.7
    command:
      - --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
    networks:
      - app-network
volumes:
  mysql:
networks:
  app-network:
    driver: bridge